spring:
  datasource:
     url: jdbc:h2:file:~/test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
         dialect: org.hibernate.dialect.H2Dialect
